apiVersion: v1
kind: Pod
metadata:
  name: cpu-spiker
spec:
  containers:
    - name: cpu-spiker
      image: vish/stress
      args: ["-cpus", "4"]
      resources:
        limits:
          cpu: "2"
          memory: "256Mi"
      volumeMounts:
        - name: log-volume
          mountPath: /logs
  volumes:
    - name: log-volume
      emptyDir: {}
